LMSWeb/Controllers/EmailTemplateController.cs
using System.Configuration;
using System.Net.Configuration;
using System.Net.Mail;
using System.Web.Mvc;
using LMSBL.Common;
using LMSBL.DBModels;
using LMSBL.Repository;
using LMSWeb.App_Start;
using LMSWeb.ViewModel;
using System.Linq;
using System.Web.Script.Serialization;
using System.Net.Http;
using System.Net;
using System.Text;
using System.IO;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System;



namespace LMSWeb.Controllers
{
    public class EmailTemplateController : Controller
    {
        EmailTemplateRepository etr = new EmailTemplateRepository();
        Exceptions newException = new Exceptions();
        // GET: EmailTemplate
        public ActionResult Index()
        {
            TblUser sessionUser = (TblUser)Session["UserSession"];
            var lstTemplate = etr.GetEmailTemplateAssigns(sessionUser.TenantId);
            return View(lstTemplate);

        }
        public ActionResult EditTemplate(int id)
        {
            try
            {
                List<tblTemplateAssign> TemplateDetails = new List<tblTemplateAssign>();
                TemplateDetails = etr.GetEmailTemplateAssignsById(id);

                return View("UpdateEmailTemplate", TemplateDetails[0]);
            }
            catch (Exception ex)
            {
                newException.AddException(ex);
                TempData["Message"] = "-1";
                return RedirectToAction("Index");

            }

        }
        
        [HttpPost, ValidateInput(false)]
        public ActionResult UpdateTemplate(tblTemplateAssign objTemplate)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var id = 0;
                    TblUser sessionUser = (TblUser)Session["UserSession"];                    
                    objTemplate.TenantId = sessionUser.TenantId;
                   
                    
                      id = etr.UpdateEmailTemplate(objTemplate);
                    
                    if (id > 0)
                    {
                       
                        TempData["Message"] = "Template Updated Successfully";
                    }
                    else
                    {
                        TempData["Message"] = "2";
                    }

                    
                }
                return View("UpdateEmailTemplate", objTemplate);

                //return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                TempData["Message"] = "2";
                newException.AddException(ex);
                return View("Index", objTemplate);
            }
        }
    }
}

LMSWeb/Controllers/ForumController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Net.Configuration;
using System.Net.Mail;
using System.Web.Mvc;
using System.Data;
using LMSBL.Common;
using LMSBL.DBModels;
using LMSBL.Repository;
using LMSWeb.App_Start;
using LMSWeb.ViewModel;
using System.Linq;
using System.Web.Script.Serialization;
using System.Net.Http;
using System.Net;
using System.Text;
using System.IO;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace LMSWeb.Controllers
{
    public class ForumController : Controller
    {
        // GET: Forum
        UserRepository userRepository = new UserRepository();
        ForumRepository fr = new ForumRepository();
        Exceptions newException = new Exceptions();
        CoursesRepository cc = new CoursesRepository();
        EmailTemplateRepository etr = new EmailTemplateRepository();
        public ActionResult Index()
        {
            TblUser sessionUser = (TblUser)Session["UserSession"];
            var lstForum = fr.GetAllForums(sessionUser.TenantId);
            return View(lstForum);
        }

        public ActionResult AddForum()
        {
            tblForum objForum = new tblForum();
            return View(objForum);
        }
        [HttpPost]
        public ActionResult AddForum(tblForum objForum)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var id = 0;
                    TblUser sessionUser = (TblUser)Session["UserSession"];
                    objForum.CreatedBy = sessionUser.UserId;
                    objForum.TenantId = sessionUser.TenantId;
                    if (objForum.ForumType == 2)
                    {
                        objForum.IsBrodcast = false;
                    }

                    if (objForum.ForumId == 0)
                    {
                        id = fr.AddForum(objForum);
                    }
                    else
                    {
                        id = fr.EditForum(objForum);
                    }
                    if (id > 0)
                    {
                        TempData["Message"] = "1";
                    }
                    else
                    {
                        TempData["Message"] = "2";
                    }

                    //return View("objForum");
                }
                return View("AddForum", objForum);
            }
            catch (Exception ex)
            {
                TempData["Message"] = "2";
                newException.AddException(ex);
                return View("AddForum", objForum);
            }
        }

        public ActionResult EditForum(int id)
        {
            try
            {
                List<tblForum> ForumDetails = new List<tblForum>();
                ForumDetails = fr.GetForumById(id);

                return View("AddForum", ForumDetails[0]);
            }
            catch (Exception ex)
            {
                newException.AddException(ex);
                TempData["Message"] = "-1";
                return RedirectToAction("Index");
                //return View("Index");
            }

        }


        public ActionResult ForumList()
        {
            TblUser sessionUser = (TblUser)Session["UserSession"];
            var lstForum = fr.GetAllForumsForLearner(sessionUser.UserId);
            return View(lstForum);
        }

        public ActionResult PostComment(int forumId)
        {
            tblForumReply objForumReply = new tblForumReply();
            TblUser sessionUser = (TblUser)Session["UserSession"];
            var lstReply = fr.GetForumReplyForLearner(forumId, sessionUser.UserId);
            objForumReply.lstReply = lstReply;
            return View(objForumReply);

        }

        public ActionResult GetComment(int forumId)
        {
            tblForumReply objForumReply = new tblForumReply();
            TblUser sessionUser = (TblUser)Session["UserSession"];
            var lstReply = fr.GetForumReplyForLearner(forumId, sessionUser.UserId);
            objForumReply.lstReply = lstReply;
            return PartialView("_CommentList",objForumReply);

        }

        public ActionResult ForumReport(int forumId)
        {
            tblForumReply objForumReply = new tblForumReply();
            TblUser sessionUser = (TblUser)Session["UserSession"];
            var lstReply = fr.GetForumReplyReportLearner(forumId, sessionUser.UserId);
            objForumReply.lstReply = lstReply;
            return View(objForumReply);

        }

        public ActionResult AddReply(int forumId,string forumReply)
        {

            TblUser sessionUser = (TblUser)Session["UserSession"];
            tblForumReply objForumReply = new tblForumReply();
            objForumReply.ForumId = forumId;
            objForumReply.UserId = sessionUser.UserId;
            objForumReply.ForumReply = forumReply;

            var status = fr.AddForumReply(objForumReply);

            return Json("OK", JsonRequestBehavior.AllowGet);
        }

        public ActionResult Getuser(int fId)
        {
            List<SelectListItem> userItems = new List<SelectListItem>();
            TblUser sessionUser = (TblUser)Session["UserSession"];

            var Users = userRepository.GetAllUsers(sessionUser.TenantId);

            foreach (var user in Users)
            {
                userItems.Add(new SelectListItem
                {
                    Text = Convert.ToString(user.FirstName + " " + user.LastName),
                    Value = Convert.ToString(user.UserId)
                });
            }

            DataSet ds = fr.GetAssignedForumUsers(fId);
            if (ds != null)
            {
                if (ds.Tables.Count > 0)
                {
                    if (ds.Tables[0].Rows.Count > 0)
                    {
                        foreach (var item in userItems)
                        {
                            DataRow[] foundUsers = ds.Tables[0].Select("UserId = " + item.Value + "");
                            if (foundUsers.Length != 0)
                            {
                                item.Selected = true;
                            }
                        }
                    }
                }
            }

            return Json(userItems, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetAssignedUsers(int fId)
        {
            List<SelectListItem> userItems = new List<SelectListItem>();
            TblUser sessionUser = (TblUser)Session["UserSession"];

            var Users = userRepository.GetAllUsers(sessionUser.TenantId);
            foreach (var user in Users)
            {
                userItems.Add(new SelectListItem
                {
                    Text = Convert.ToString(user.FirstName + " " + user.LastName),
                    Value = Convert.ToString(user.UserId)
                });
            }

            List<tblForumAssign> lstforumAssignedUsers = new List<tblForumAssign>();
            lstforumAssignedUsers = fr.GetForumAssingedDetailedUserslist(fId);

            return Json(lstforumAssignedUsers, JsonRequestBehavior.AllowGet);
        }
        public ActionResult AssignForumTouser(string jsonData, int fId)
        {
            try
            {
                TblUser sessionUser = (TblUser)Session["UserSession"];
                List<tblForum> ForumDetails = new List<tblForum>();


                JavaScriptSerializer json_serializer = new JavaScriptSerializer();
                json_serializer.MaxJsonLength = int.MaxValue;
                object[] objData = null;
                if (!string.IsNullOrEmpty(jsonData))
                {
                    objData = (object[])json_serializer.DeserializeObject(jsonData);
                }
                var result = fr.AssignForumToDB(objData, fId);
                //if (result == 1)
                //{
                //    // TblUser sessionUser = (TblUser)Session["UserSession"];
                //    var lstTemplate = etr.GetEmailTemplateAssigns(sessionUser.TenantId);
                //    ForumDetails = fr.GetForumById(fId);
                //    foreach (Dictionary<string, object> item in objData)
                //    {
                //        var emailBody = lstTemplate[10].EmailBody;
                //        var objUser = userRepository.GetUserById(Convert.ToInt32(item["UserId"]));
                //        emailBody = emailBody.Replace("{UserName}", objUser[0].FirstName + " " + objUser[0].LastName);
                //        emailBody = emailBody.Replace("{ForumName}", ForumDetails[0].Title);
                //        emailBody = emailBody.Replace("{DueDate}", Convert.ToString(item["DueDate"]));
                //        emailBody = emailBody.Replace("{Admin}", objUser[0].TenantName);
                //        var emailSubject = lstTemplate[10].EmailSubject + "-" + ForumDetails[0].Title;
                //        tblEmails objEmail = new tblEmails();

                //        objEmail.EmailTo = objUser[0].EmailId;
                //        objEmail.EmailSubject = emailSubject;
                //        objEmail.EmailBody = emailBody;
                //        objEmail.Activityid = fId;
                //        objEmail.Activitytype = "Curriculum";
                //        objEmail.Duedate = Convert.ToDateTime(item["DueDate"]);
                //        bool status = cc.CheckInsertEmail(objEmail);
                //        if (!status)
                //        {
                //            var emailResult = userRepository.InsertEmail(objEmail);

                //        }

                //    }
                //}
            }
            catch (Exception ex)
            {
                newException.AddException(ex);
            }

            return Json(HttpStatusCode.OK, JsonRequestBehavior.AllowGet);
        }

    }
}

LMSWeb/Views/EmailTemplate/Index.cshtml
@model List<LMSBL.DBModels.tblTemplateAssign>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutNew.cshtml";
}

<div class="container-fluid mt-4 mb-4 pl-4 pr-4">
    @if (!string.IsNullOrEmpty(Convert.ToString(TempData["Message"])))
    {
        if (Convert.ToString(TempData["Message"]) == "-1")
        {
            <script>
swal.fire({
                    icon: 'error',
                    title: 'Oops...',
                    text: 'Something went Wrong!'
                })</script>
        }

    }
    <div class="mt-5 pt-3 pl-3 pr-3 course-list-container list-box">
        <div class="row">
            <div class="col-lg-6 col-md-12 search-container test">
                <i class="fas fa-search"></i>
                <input class="search-box" type="text" id="txtSearch" placeholder="Search Forum by name..." />
            </div>
            @* <div class="col-lg-6 col-md-12 text-right">
            <ul class="list-inline progress-list mt-2">
                <li class="list-inline-item">
                    <a href="@Url.Action("AddForum", "Forum")">
                        <button class="btn btn-secondary dropdown-toggle create-learning-btn" type="button">
                            <i class="fas fa-plus-circle"></i> Add Forum
                        </button>
                    </a>
                </li>
            </ul>
        </div>*@
        </div>
        <div class="row mt-3" id="dvActivityData">
            <div class="table-responsive">
                <table class="table" id="activityTable">
                    <thead>
                        <tr>
                            <th scope="col">Sr No.</th>
                            <th scope="col">Template Subject</th>
                            <th scope="col">Template Body</th>
                            <th scope="col">Date Created</th>
                            <th scope="col" style="text-align:center;" class="action-column">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null)
                        {
                            var index = 0;
                            if (Model.Count > 0)
                            {

                                foreach (var template in Model)
                                {
                                    index++;
                                    <tr>
                                        <td class="add-column-padding">@index</td>
                                        <td>@template.EmailSubject</td>
                                        <td style="max-width:200px;">@template.EmailBody</td>
                                        
                                        <td>@template.DateCreated</td>                                        

                                        <td style="text-align:center;">
                                            <a href="@Url.Action("EditTemplate", "EmailTemplate", new { id = template.TemplateId })" class="login" title="Update"><img src="~/assets/images/shape_editUser.png" /></a>&nbsp;&nbsp;
                                            
                                        </td>

                                    </tr>
                                }
                            }
                            else
                            {
                                <tr>
                                    <td colspan="8" align="center">No Email Template Available</td>
                                </tr>
                            }
                        }
                        else
                        {
                            <tr>
                                <td colspan="8">No Email Template Available</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script>
$(document).ready(function () {
        $('#activityTable').DataTable({
            
            "paging": true,
            "ordering": true,
            "rowReorder":true,
            "info": true,
            "bFilter": true,
            "pageLength": 10,
            "pagingType": "simple_numbers",
            aoColumnDefs: [
                {
                    bSortable: false,
                    aTargets: [-1]
                }
            ]
            //language: {
            //    paginate: {
            //        next: '&#8594;', // or '→'
            //        previous: '&#8592;' // or '←'
            //    }
            //}
        });

        $('#activityTable_filter').hide();

        $('#txtSearch').on('keyup', function () {

            $.fn.dataTable.ext.search.push(function (settings, searchData) {
                var term = $('#txtSearch').val().toLowerCase()
                for (var i = 0; i < searchData.length; i++) {
                    if (searchData[i].toLowerCase().indexOf(term) == 0) {
                        return true;
                    }
                }
                return false;
            });
            var table = $('#activityTable').DataTable();
            table.draw();
            table.rowReordering();
        });

    });</script>

<style>

    table.dataTable thead .sorting_asc {
        background: url("https://cdn.datatables.net/1.10.0/images/sort_asc.png") no-repeat center left;
    }

    table.dataTable thead .sorting_desc {
        background: url("https://cdn.datatables.net/1.10.0/images/sort_desc.png") no-repeat center left;
    }

    table.dataTable thead .sorting {
        background: url("https://cdn.datatables.net/1.10.0/images/sort_both.png") no-repeat center left;
    }
</style>

LMSWeb/Views/EmailTemplate/UpdateEmailTemplate.cshtml
@model LMSBL.DBModels.tblTemplateAssign
@{
    ViewBag.Title = "Update Email Template";
    Layout = "~/Views/Shared/_LayoutNew.cshtml";
}

@using (Html.BeginForm("UpdateTemplate", "EmailTemplate", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="container-fluid mt-4 mb-4 pl-4 pr-4">
    @if (!string.IsNullOrEmpty(Convert.ToString(TempData["Message"])))
    {
        <script>
            swal.fire("Template Updated Successfully")
                .then((value) => {
                    window.location.href = "Index";
                });
        </script>

    }
    <div class="row" style="margin-bottom:25px;margin-left:275px;">
        <div class="col">
            <h4 class="title-color">Update Email Template</h4>
        </div>
    </div>
    <div class="row justify-content-center h-100">
        <div class="col align-self-center add-user-section list-box">
            <div class="row pt-5 pl-4">
                @Html.HiddenFor(Model => Model.TemplateId)

                @Html.TextBoxFor(Model => Model.EmailSubject, new { @class = "input200 d-block", placeholder = "Email Subject" })

                @Html.TextAreaFor(Model => Model.EmailBody, new { @class = "input100", id = "editarea" })



            </div>
            <div class="row justify-content-end pr-4 mt-2">
                <button type="submit" name="submit" id="btnUpdate" value="save" class="btn btn-primary profle-submit-btn mr-4"><img src="~/assets/images/check-img.png" /> Update</button>

            </div>
        </div>
    </div>
</div>
}


<!-- include summernote css/js -->
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.15/dist/summernote.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.15/dist/summernote.min.js"></script>

<script src="~/assets/Quiz.js"></script>

<script >
    $(document).ready(function () {
        $('#editarea').summernote();
    });
      
</script>