LMSWeb/Controllers/TenantController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Web;
using System.Web.Mvc;
using LMSBL.Common;
using LMSBL.DBModels;
using LMSBL.Repository;


namespace LMSWeb.Controllers
{


    public class TenantController : Controller
    {
        TenantRepository tr = new TenantRepository();
        Exceptions newException = new Exceptions();
        UserRepository ur = new UserRepository();
        RolesRepository rr = new RolesRepository();

        // GET: Tenant
        public ActionResult Index()
        {
            try
            {
                List<TblTenant> lstAllTenants = new List<TblTenant>();
                lstAllTenants = tr.GetAllTenants();
                return View(lstAllTenants);
            }
            catch (Exception ex)
            {
                newException.AddException(ex);
                return View();
            }
        }

        public ActionResult AddTenant()
        {
            try
            {
                TblTenant objEditData = new TblTenant();
                return View(objEditData);
            }
            catch (Exception ex)
            {
                newException.AddException(ex);
                return View();
            }
        }

        [HttpPost]
        public ActionResult AddTenant(TblTenant objTenant, HttpPostedFileBase file)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (objTenant.TenantId == 0)
                    {
                        var result = tr.GetTenantByName(objTenant.TenantName);
                        if (!result)
                        {
                            TempData["Message"] = "Tenant Already Exist";
                            return View(objTenant);
                        }
                    }
                    if (file != null)
                    {
                        var logoURL = System.Configuration.ConfigurationManager.AppSettings["LogoURL"];
                        var logoPhysicalURL = System.Configuration.ConfigurationManager.AppSettings["logoPhysicalURL"];                        
                        string filePhysicalPath = System.IO.Path.Combine(logoPhysicalURL + "\\" + objTenant.TenantName + ".jpg");
                        string path = System.IO.Path.Combine(logoURL + "\\" + objTenant.TenantName + ".jpg");
                        file.SaveAs(filePhysicalPath);                        
                        objTenant.Logo = path;
                    }
                    
                    int rows = 0;
                    if (objTenant.TenantId == 0)
                        rows = tr.AddTenant(objTenant);
                    else
                        rows = tr.EditTenants(objTenant);
                    if (rows != 0)
                    {
                        return RedirectToAction("AddTenantUser", new { @id = objTenant.TenantId });
                    }
                    else
                    {
                        return View(objTenant);
                    }

                }
                return View(objTenant);
            }
            catch (Exception ex)
            {
                newException.AddException(ex);
                return View();
            }
        }

        public ActionResult EditTenant(int id)
        {
            try
            {
                List<TblTenant> tenantDetails = new List<TblTenant>();
                tenantDetails = tr.GetTenantById(id);
                TblTenant objEditData = new TblTenant();
                objEditData = tenantDetails[0];
                return View(objEditData);
            }
            catch (Exception ex)
            {
                newException.AddException(ex);
                return View();
            }
        }

        [HttpPost]
        public ActionResult EditTenant(TblTenant objTenant)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int rows = tr.EditTenants(objTenant);
                    if (rows != 0)
                    {
                        return RedirectToAction("AddTenantUser", new { @id = objTenant.TenantId });
                    }
                    else
                    {
                        return View(objTenant);
                    }
                }
                return View(objTenant);
            }
            catch (Exception ex)
            {
                newException.AddException(ex);
                return View();
            }
        }

        [HttpPost, ActionName("DeleteTenant")]
        public ActionResult DeleteConfirmTenant(int id)
        {
            try
            {
                Response response = new Response();
                List<TblTenant> objTenantList = tr.GetTenantById(id);
                TblTenant objTenant = objTenantList[0];
                if (ModelState.IsValid)
                {
                    if (objTenant.IsActive == true)
                    {
                        objTenant.IsActive = false;
                    }
                    else
                    {
                        objTenant.IsActive = true;
                    }
                    int rows = tr.DeleteTenants(objTenant);
                    if (rows != 0)
                    {
                        response.StatusCode = 1;
                    }
                    else
                    {
                        response.StatusCode = 0;
                    }
                }
                return Json(response.StatusCode, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                newException.AddException(ex);
                return View();

            }
        }

        public ActionResult VerifyTenantDomain(string Domain)
        {
            try
            {
                int isAvailable = 0;//Need to change this tr.VerifyTenantDomain(Domain);
                return Json(isAvailable, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                newException.AddException(ex);
                return View();
            }
        }

        public ActionResult AddTenantUser(int id)
        {
            try
            {
                TblUser objUserData = new TblUser
                {
                    UserRoles = rr.GetAllRoles(),
                    Tenants = tr.GetAllTenants()
                };
                objUserData.TenantId = id;
                return View(objUserData);
            }
            catch (Exception ex)
            {
                newException.AddException(ex);
                return View();
            }
        }

        [HttpPost]
        public ActionResult SaveTenantUser(TblUser objUser)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    TblUser sessionUser = (TblUser)Session["UserSession"];
                    objUser.CreatedBy = sessionUser.UserId;
                    objUser.IsActive = true;
                    int rows = 0;
                    if (objUser.UserId == 0)
                        rows = ur.AddUser(objUser);
                    else
                        rows = ur.EditUser(objUser);
                    if (rows != 0)
                    {
                        TempData["Message"] = "Saved Successfully";
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        TempData["Message"] = "Not Saved Successfully";
                        return View("AddTenantUser",objUser);
                    }
                }
                return View("AddTenantUser", objUser);
            }
            catch (Exception ex)
            {
                newException.AddException(ex);
                return View(objUser);
            }

        }
    }
}

LMSWeb/Views/Tenant/AddTenant.cshtml
@model LMSBL.DBModels.TblTenant
@{
    ViewBag.Title = "Add Client";
    Layout = "~/Views/Shared/_LayoutNew.cshtml";
}


@using (Html.BeginForm("AddTenant", "Tenant", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    
    <div class="container-fluid mt-4 mb-4 pl-4 pr-4">
        @if (!string.IsNullOrEmpty(Convert.ToString(TempData["Message"])))
        {
            <script>
                swal.fire("Course Saved Successfully")
                    .then((value) => {
                        window.location.href = "Index";
                    });
            </script>

        }
        <div class="row justify-content-center h-100">
            <div class="col align-self-center add-user-section ">
                <div class="col">
                  <h4 class="mt-3 ml-2 mb-3">New Client</h4>
                   
                </div>
                <div class="row pt-5 pl-4">
                    <div class="col-sm-6">

                        @Html.HiddenFor(model => model.TenantId)
                        @Html.TextBoxFor(model => model.TenantName, new { @class = "input100", placeholder = "ClientName" })
                        @Html.TextBoxFor(model => model.TenantDomain, new { @class = "input100", placeholder = "ClientDomain" })
                        @Html.TextBoxFor(model => model.ActivationFrom, new { @class = "input100", @id = "DtActivitionFrom", @autocomplete = "off", placeholder = "ActivationFrom" })
                        @Html.TextBoxFor(model => model.ActivationTo, new { @class = "input100", @id = "DtActivitionTo", @autocomplete = "off", placeholder = "ActivationTo" })
                        @Html.TextBoxFor(model => model.NoOfUserAllowed, new { @class = "input100", placeholder = "NoOfUserAllowed" })
                    </div>


                    <div class="col-sm-6">                     
                        
                        <div>

                            <input type="button" id="btnTenantDomainName" value="verify" class="btn btn-primary profle-submit-btn mr-4" />
                            <label id="lblerrorDomain" style="display:none;margin-left:263px;"></label>
                        </div>
                        <div>
                            
                            @Html.LabelFor(model => model.Logo, new { @class = "" })
                        </div>
                        <div>
                            <input type="file" name="file" id="file" style="width: 100%;" onchange="show(this)" />
                            <div>
                                <small>(File should not exceed 1 MB)</small>
                            </div>
                            <p></p>
                            <div class="col-3 p-0"> <img id="user_img" height="100" width="200" /> </div>

                        </div>
                    </div>




                    
                </div>
                <div class="row justify-content-end pr-4">
                    <button type="submit" id="btnTenantSubmit" class="btn btn-primary profle-submit-btn mr-4"><b>Submit</b></button>
                    <button type="submit" onclick="location.href='@Url.Action("Index", "Tenant")';return false;"
                            class="btn btn-outline-primary cancel-btn">
                        <b>Cancel</b>
                    </button>

                </div>
            </div>
        </div>
     </div>
  }

            <script src="~/assets/Validations.js"></script>
            <script type="text/javascript">
                $(document).ready(function () {
                    console.log('Ready..!');

                    $('#DtActivitionFrom').datepicker({
                        format: 'mm/dd/yyyy',
                        showWeek: true,
                        startDate: new Date()
                    });

                    $('#DtActivitionTo').datepicker({
                        format: 'mm/dd/yyyy',
                        showWeek: true,
                        startDate: new Date()
                    });


                    $("#txtdomainName").keypress(function () {
                        $("#lblerrorDomain").hide()
                    });

                    $("#btnTenantDomainName").click(function () {
                        if ($('#TenantDomain').val() == "") {
                            alert("Please enter Client Domain");
                            return false;
                        }
                        else {
                            VerifyTenantDomain($('#TenantDomain').val());
                        }
                    })


                });
                function show(input) {
                    if (input.files && input.files[0]) {
                        var filerdr = new FileReader();
                        filerdr.onload = function (e) {
                            $('#user_img').attr('src', e.target.result);
                        }
                        filerdr.readAsDataURL(input.files[0]);
                    }
                }

                function VerifyTenantDomain(DominName) {
                    $.ajax({
                        url: "/Tenant/VerifyTenantDomain?Domain=" + DominName,
                        type: "GET",
                        contentType: "application/json;charset=UTF-8",
                        dataType: "json",
                        success: function (result) {
                            console.log(result)
                            if (result == 1) {
                                $("#lblerrorDomain").text("Domain Name is not Available !!!");
                                $("#lblerrorDomain").css("color", "Red");
                            }
                            else {
                                $("#lblerrorDomain").text("Domain Name is Available !!!");
                                $("#lblerrorDomain").css("color", "Green");
                            }
                            $("#lblerrorDomain").show();
                        },
                        error: function (errormessage) {
                            alert(errormessage.responseText);
                        }
                    });
                }
            </script>

LMSWeb/Views/Tenant/AddTenantUser.cshtml
@model LMSBL.DBModels.TblUser
@{
    ViewBag.Title = "Add Admin";
    Layout = "~/Views/Shared/_LayoutNew.cshtml";
}

@using (Html.BeginForm("SaveTenantUser", "Tenant", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="container-fluid mt-4 mb-4 pl-4 pr-4">
        <div class="row justify-content-center h-100">
            <div class="col align-self-center add-user-section ">
                <div class="col">
                  <h4 class="mt-3 ml-2 mb-3">Add Admin</h4>
                    
                </div>
                <div class="row pt-5 pl-4">
                    <div class="col-sm-6">
                        @Html.HiddenFor(model => model.UserId)
                        @Html.HiddenFor(model => model.TenantId)

                        @Html.TextBoxFor(model => model.FirstName, new { @class = "input100", placeholder = "FirstName" })

                        @*@Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })*@

                        @Html.TextBoxFor(model => model.LastName, new { @class = "input100", placeholder = "LastName" })
                        @*<span class="required">&#10026;</span>*@
                        @*@Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })*@

                        @Html.TextBoxFor(model => model.EmailId, new { @class = "input100", placeholder = "EmailId" })
                        @*<span class="required">&#10026;</span>*@
                        @*@Html.ValidationMessageFor(model => model.EmailId, "", new { @class = "text-danger" })*@

                        
                        @*<span class="required">&#10026;</span>*@
                        @*@Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })*@
                    </div>
                    <div class="col-sm-6">
                        @Html.TextBoxFor(model => model.DOB, "{0:MM/dd/yyyy}", new { @class = "input100 datepicker", @id = "dtDOB", @readonly = "readonly", @autocomplete = "off", placeholder = "DateOfBirth" })

                        @*@Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })*@

                        @Html.TextBoxFor(model => model.ContactNo, new { @class = "input100", placeholder = "ContactNo" })

                        @*@Html.ValidationMessageFor(model => model.ContactNo, "", new { @class = "text-danger" })*@
                        @*@Html.LabelFor(model => model.RoleName, new { @class = "col-3 p-0" })*@
                        @Html.DropDownListFor(x => Model.RoleId, new SelectList(Model.UserRoles, "RoleId", "RoleName"), htmlAttributes: new { @class = "input100", id = "TenantUserRoles" })
                        @*<span class="required">&#10026;</span>*@
                        @*@Html.ValidationMessageFor(x => Model.UserRoles[0].RoleId, "", new { @class = "text-danger" })*@
                        

                    </div>               
                </div>
                    <div class="row justify-content-end pr-4">
                        <div >
                            <button type="submit" id="btnUserSubmit" class="btn btn-primary profle-submit-btn mr-4"><b>Submit</b></button>
                            <button type="submit" onclick="location.href='@Url.Action("Index", "Tenant")';return false;"
                                    class="btn btn-outline-primary cancel-btn">
                                <b>Cancel</b>
                            </button>

                        </div>
                    </div>
                </div>
        </div>
    </div>


}
<script src="~/assets/Validations.js"></script>

<script type="text/javascript">
    $(document).ready(function () {

        $('#dtDOB').datepicker({
            format: 'mm/dd/yyyy',
            showWeek: true
        });
    });
</script>

LMSWeb/Views/Tenant/EditTenant.cshtml
@model LMSBL.DBModels.TblTenant
@{
    ViewBag.Title = "Edit Client";
    Layout = "~/Views/Shared/_LayoutNew.cshtml";
}


@using (Html.BeginForm("AddTenant", "Tenant", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="container-fluid mt-4 mb-4 pl-4 pr-4">
        @if (!string.IsNullOrEmpty(Convert.ToString(TempData["Message"])))
        {
            <script>
                swal.fire("Course Saved Successfully")
                    .then((value) => {
                        window.location.href = "Index";
                    });
            </script>

        }
        <div class="row justify-content-center h-100">
            <div class="col align-self-center add-user-section ">
                <div class="col">
                    <h4 class="mt-3 ml-2 mb-3">Edit Client</h4>

                </div>
                <div class="row pt-5 pl-4">

                    <div class="col-sm-6">
                        @Html.HiddenFor(model => model.TenantId)
                        @Html.TextBoxFor(model => model.TenantName, new { @class = "input100", @readonly = "readonly", placeholder = "ClientName" })
                        @Html.TextBoxFor(model => model.TenantDomain, new { @class = "input100", @readonly = "readonly", placeholder = "ClientDomain" })
                        @Html.TextBoxFor(model => model.ActivationFrom, "{0:MM/dd/yyyy}", new { @class = "input100", @id = "DtActivitionFrom", @autocomplete = "off", placeholder = "ActivationFrom" })
                        @Html.TextBoxFor(model => model.ActivationTo, "{0:MM/dd/yyyy}", new { @class = "input100", @id = "DtActivitionTo", @autocomplete = "off", placeholder = "ActivationTo" })
                        @Html.TextBoxFor(model => model.NoOfUserAllowed, new { @class = "input100", placeholder = "NoOfUserAllowed" })
                    </div>

                    <div class="col-sm-6">
                        <div>

                            <input type="button" id="btnTenantDomainName" value="verify" class="btn btn-primary profle-submit-btn mr-4" />
                            <label id="lblerrorDomain" style="display:none;margin-left:263px;"></label>
                        </div>
                        <div>
                            @Html.LabelFor(model => model.Logo, new { @class = "" })
                        </div>
                        <div>
                            <input type="file" name="file" id="file" style="width: 100%;" onchange="show(this)" />
                            <div>
                                <small>(File should not exceed 1 MB)</small>
                            </div>
                            
                            <div> <img id="user_img" height="100" width="200" src="@Model.Logo" /> </div>
                        </div>

                    </div>


                    <div class="col-sm-6">
                        
                        
                            <button type="submit" id="btnTenantSubmit" class="btn btn-primary profle-submit-btn mr-4"><b>Submit</b></button>
                            <button type="submit" onclick="location.href='@Url.Action("Index", "Tenant")';return false;"
                                    class="btn btn-outline-primary cancel-btn">
                                <b>Cancel</b>
                            </button>

                        
                    </div>

                </div>
            </div>
    </div>
        </div>

}

<script src="~/assets/Validations.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        console.log('Ready..!');

        $('#DtActivitionFrom').datepicker({
            format: 'mm/dd/yyyy',
            showWeek: true,
            startDate: new Date()
        });

        $('#DtActivitionTo').datepicker({
            format: 'mm/dd/yyyy',
            showWeek: true,
            startDate: new Date()
        });


        $("#txtdomainName").keypress(function () {
            $("#lblerrorDomain").hide()
        });

        $("#btnTenantDomainName").click(function () {
            if ($('#TenantDomain').val() == "") {
                alert("Please enter Client Domain");
                return false;
            }
            else {
                VerifyTenantDomain($('#TenantDomain').val());
            }
        })


    });
    function show(input) {
        if (input.files && input.files[0]) {
            var filerdr = new FileReader();
            filerdr.onload = function (e) {
                $('#user_img').attr('src', e.target.result);
            }
            filerdr.readAsDataURL(input.files[0]);
        }
    }

    function VerifyTenantDomain(DominName) {
        $.ajax({
            url: "/Tenant/VerifyTenantDomain?Domain=" + DominName,
            type: "GET",
            contentType: "application/json;charset=UTF-8",
            dataType: "json",
            success: function (result) {
                console.log(result)
                if (result == 1) {
                    $("#lblerrorDomain").text("Domain Name is not Available !!!");
                    $("#lblerrorDomain").css("color", "Red");
                }
                else {
                    $("#lblerrorDomain").text("Domain Name is Available !!!");
                    $("#lblerrorDomain").css("color", "Green");
                }
                $("#lblerrorDomain").show();
            },
            error: function (errormessage) {
                alert(errormessage.responseText);
            }
        });
    }
</script>

LMSWeb/Views/Tenant/GetAllActiveTenants.cshtml
@model List<LMSBL.DBModels.TblTenant>
@{
    ViewBag.Title = "Get All Active Tenants";
}

<table id="example" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Domain</th>
            <th scope="col">Activation From</th>
            <th scope="col">Activation To</th>
            <th scope="col">Is Active</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var tenent in Model)
        {
            <tr>
                <th scope="row">@tenent.TenantId</th>
                <td>@tenent.TenantName</td>
                <td><a style="color:blue;" href="@tenent.DomainUrl" target="_blank">@tenent.TenantDomain</a></td>
                <td>@tenent.ActivationFrom.Value.ToString("dd-MMM-yyyy")</td>
                <td>@tenent.ActivationTo.Value.ToString("dd-MMM-yyyy")</td>
                <td style="color:green;text-align:center"><i class="fas fa-fw fa-check"></i></td>
                <td>
                    <a href="@Url.Action("EditTenant", "Tenant",new { id=tenent.TenantId})">
                        <i class="fas fa-fw fa-edit" title="Edit Tenant"></i>
                    </a>
                </td>
                <td>
                    @*<a href="@Url.Action("DeleteTenant", "Tenant",new { id=tenent.TenantId,isActive=true})">
                            <i class="fas fa-fw fa-trash" title="Deactivate Tenant"></i>
                        </a>*@
                    <button type="submit" class="btn btn-link" onclick="ConfirmationAlert('@tenent.TenantName',@tenent.TenantId,true)">
                        <i class="fas fa-fw fa-trash" title="Deactivate Tenant"></i>
                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>

@*<body>

    <div class="row">
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
            <div class="card">
                <div class="card-body">

                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Name</th>
                                <th scope="col">Domain</th>
                                <th scope="col">Activation From</th>
                                <th scope="col">Activation To</th>
                                <th scope="col">Is Active</th>
                                <th scope="col" colspan="2">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var tenent in Model)
                            {
                                <tr>
                                    <th scope="row">@tenent.TenantId</th>
                                    <td>@tenent.TenantName</td>
                                    <td><a style="color:blue;" href="@tenent.DomainUrl" target="_blank">@tenent.TenantDomain</a></td>
                                    <td>@tenent.ActivationFrom.Value.ToString("dd-MMM-yyyy")</td>
                                    <td>@tenent.ActivationTo.Value.ToString("dd-MMM-yyyy")</td>
                                    <td style="color:green;text-align:center"><i class="fas fa-fw fa-check"></i></td>
                                    <td>
                                        <a href="@Url.Action("EditTenant", "Tenant",new { id=tenent.TenantId})">
                                            <i class="fas fa-fw fa-edit" title="Edit Tenant"></i>
                                        </a>
                                    </td>
                                    <td>
                                        @*<a href="@Url.Action("DeleteTenant", "Tenant",new { id=tenent.TenantId,isActive=true})">
                                                <i class="fas fa-fw fa-trash" title="Deactivate Tenant"></i>
                                            </a
                                        <button type="submit" class="btn btn-link" onclick="ConfirmationAlert('@tenent.TenantName',@tenent.TenantId,true)">
                                            <i class="fas fa-fw fa-trash" title="Deactivate Tenant"></i>
                                        </button>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>>*@
<script type="text/javascript">


    function ConfirmationAlert(Name, Id, IsActive) {
        var data = {
            id: Id
        }
        var strDelete = "";
        if (IsActive == true) {
            strDelete = "Deactivate";
        }
        else {
            strDelete = "Activate";
        }
        swal({
            title: "Are you sure you want to " + strDelete + " Tenant " + Name + " ?",
            text: "You are going to " + strDelete + " the tenant",
            type: "warning",
            showCancelButton: true,
            confirmButtonClass: "btn-danger",
            confirmButtonText: strDelete,
            cancelButtonText: "Cancel",

        }).then((isConfirm) => {
            if (isConfirm.value == true) {
                $.ajax({
                    url: "/Tenant/DeleteTenant",
                    type: "POST",
                    contentType: "application/json;charset=UTF-8",
                    dataType: "json",
                    data: JSON.stringify(data),
                    success: function (result) {
                        var baseUrl = "/Tenant/Index";
                        if (result == 1) {
                            window.location.href = baseUrl
                        }
                        else {
                            alert('Something went wrong');
                        }

                    },
                    error: function (errormessage) {
                        alert(errormessage.responseText);
                    }
                });

            } else {
                swal("Cancelled", "Cancelled", "error");
            }
        });
    }
</script>